const state={lessons:[],level:'All levels',topic:'All topics'};
const topics=['Politics','Sport','Science','Environment','Business','Culture','Technology','Health'];
const imageFallback='https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=700&q=80';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function lessonMeta(lesson){return `<span>▥ ${esc(lesson.level)}</span><span>▱ ${esc(lesson.topic)}</span><span>▣ ${esc(lesson.date)}</span>`}
function renderToday(){const lesson=state.lessons[0];if(!lesson)return;document.querySelector('#today').innerHTML=`<div class="today-copy"><span class="pill">TODAY'S LESSON</span><h2>${esc(lesson.title)}</h2><div class="meta">${lessonMeta(lesson)}</div><p>${esc(lesson.description)}</p><div class="actions"><a class="button" href="${esc(lesson.presentation)}" target="_blank" rel="noopener">▶ &nbsp;View presentation</a><a class="button outline" href="${esc(lesson.worksheet)}" target="_blank" rel="noopener" download>⇩ &nbsp;Download worksheet</a></div></div><a class="lesson-image" href="${esc(lesson.presentation)}" target="_blank" rel="noopener" style="background-image:linear-gradient(90deg,rgba(0,30,60,.3),rgba(0,30,60,.05)),url('${esc(lesson.image||imageFallback)}')" aria-label="Open ${esc(lesson.title)} presentation"></a>`}
function renderFilters(){const levels=['All levels','B1','B2','C1'];const html=[...levels.map(l=>`<button class="${state.level===l?'selected':''}" data-level="${l}">${l}</button>`),'<span class="divider"></span>',...topics.map(t=>`<button class="${state.topic===t?'selected':''}" data-topic="${t}">${t}</button>`)].join('');document.querySelector('#filters').innerHTML=html;document.querySelectorAll('#filters button').forEach(button=>button.addEventListener('click',()=>{if(button.dataset.level)state.level=button.dataset.level;if(button.dataset.topic)state.topic=state.topic===button.dataset.topic?'All topics':button.dataset.topic;renderFilters();renderGrid()}))}
function renderGrid(){const filtered=state.lessons.filter((l,i)=>(i>0)&& (state.level==='All levels'||l.level===state.level)&&(state.topic==='All topics'||l.topic===state.topic));document.querySelector('#lessonGrid').innerHTML=filtered.map(l=>`<article class="lesson-card"><a href="${esc(l.presentation)}" target="_blank" rel="noopener"><div class="thumb" style="background-image:url('${esc(l.image||imageFallback)}')"></div></a><div class="card-body"><h3>${esc(l.title)}</h3><p>${lessonMeta(l)}</p><div class="card-links"><a href="${esc(l.presentation)}" target="_blank" rel="noopener">Presentation →</a><a href="${esc(l.worksheet)}" target="_blank" rel="noopener" download>Worksheet ↓</a></div></div></article>`).join('');document.querySelector('#noResults').hidden=filtered.length>0}
async function init(){try{const response=await fetch('lessons.json');state.lessons=await response.json();renderToday();renderFilters();renderGrid()}catch(error){document.querySelector('#today').innerHTML='<p>Lessons could not be loaded. Please try again shortly.</p>';console.error(error)}}
document.querySelector('#searchButton').addEventListener('click',()=>{const query=prompt('Search lesson titles:');if(query){const match=state.lessons.find(l=>l.title.toLowerCase().includes(query.toLowerCase()));if(match){document.querySelector('#latest').scrollIntoView();}else alert('No lesson found.')}});init();
